### What's the NumPy function to convert my_list into a NumPy array?

#You've successfully covered creating, filtering, aggregating, combining, and reshaping arrays. These are the most important building blocks of NumPy.

In [41]:
import numpy as np

In [42]:
my_list = [5,12, 8, 20, 10, 15, 3]

##What's the NumPy function to convert my_list into a NumPy array?

In [43]:
my_array = np.array(my_list)

#  i want greater than 10

In [44]:
filtered_array = my_array[my_array > 10]

In [45]:
print(my_array)

[ 5 12  8 20 10 15  3]

In [46]:
print(filtered_array)

[12 20 15]

In [47]:
avg=filtered_array.mean()
#print(avg)

In [48]:
print(avg)

15.666666666666666

In [49]:
temperatures_celsius = [20.5, 18.0, 22.1, 19.5, 25.0, 17.8]

In [50]:
cel_array=np.array(temperatures_celsius)

In [51]:
farhen_array=(cel_array*(9/5))+ 32

$Fahrenheit = Celsius \times \frac{9}{5} + 32$

In [52]:
print(farhen_array)

[68.9  64.4  71.78 67.1  77.   64.04]

In [53]:


# This is our list of lists
abc = [
 [5, 8, 10],
 [3, 4, 9],
 [5, 8, 10],
 [3, 4, 9],
 [5, 8, 10],
 [3, 4, 9],
 [5, 8, 10],
 [3, 4, 9],
 [5, 8, 10],
 [3, 4, 9]
]



# And this is how we make it a 2D array
sales = np.array(abc)

In [54]:
print(sales)

[[ 5  8 10]
 [ 3  4  9]
 [ 5  8 10]
 [ 3  4  9]
 [ 5  8 10]
 [ 3  4  9]
 [ 5  8 10]
 [ 3  4  9]
 [ 5  8 10]
 [ 3  4  9]]

In [55]:
sales.sum(axis=1)

array([23, 16, 23, 16, 23, 16, 23, 16, 23, 16])

#sales.sum(axis=0) -> Summed columns (Daily totals)

sales.sum(axis=1) -> Summed rows (Salesperson totals)

In [56]:
sales.sum(axis=0)

array([40, 60, 95])

#How would you start by selecting only the numbers in the sales array that are greater than 7?

In [57]:
newsale = sales[sales > 7]

##Now, how do you find the average of this newsale array?

In [58]:
avg=newsale.mean()

In [59]:
print(avg)

9.0

#                                     2 array

In [60]:
array_a = np.array([[1, 2], [3, 4]])

In [61]:
array_b = np.array([[5, 6], [7, 8]])

In [62]:
print(array_a)

[[1 2]
 [3 4]]

In [63]:
print(array_b)

[[5 6]
 [7 8]]

In [64]:
np.vstack((array_a, array_b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
np.hstack((array_a, array_b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#For np.hstack() (horizontal stacking ↔️), the number of rows must be the same. The number of columns can be different.

For np.vstack() (vertical stacking ↕️), the number of columns must be the same.

#Let's try a new one that combines creating and reshaping.

#Problem: We want to create a 3x4 array (3 rows, 4 columns) that contains #the numbers 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, and 11.

In [66]:
a=np.arange(12)

In [67]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [68]:
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
v=[[88, 92],
 [75, 80],
 [95, 90]]
scores=np.array(v)
print(scores)

[[88 92]
 [75 80]
 [95 90]]

##How would you find the average score for each test

In [70]:
scores.mean(axis=0)

array([86.        , 87.33333333])

##how would you find the average score for each student?

In [71]:
scores.mean(axis=1)

array([90. , 77.5, 92.5])

In [72]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 20, 30])

In [73]:
c=a+b

In [74]:
for i in range(0,8):
  for j in range(0,8):
    if(i%2==0):
      if(j%2==0):
        print("*",end=" ")
      else:
        print("0",end=" ")
    if(i%2==1):
      if(j%2==1):
        print("0",end=" ")
      else:
        print("*",end=" ")
  print("\n")

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

* 0 * 0 * 0 * 0

In [75]:
import numpy as np

In [76]:
lst = [1,2,3,4]
print(type(lst))
arr = np.array(lst)
print(type(arr))
arr = np.array(lst, ndmin = 2)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4]]

In [77]:
import pandas as pd

In [78]:
df=pd.read_excel("/content/googleplaystore.csv.xlsx")

In [79]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [80]:
print(c)

[[11 22 33]
 [14 25 36]
 [17 28 39]]

In [81]:
l = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

m = np.array([[10], [20], [30]])

In [82]:
print(l+m)

[[11 12 13]
 [24 25 26]
 [37 38 39]]

 Creating Arrays: Using np.array(), np.arange()
Indexing & Filtering: Using boolean masks (e.g., arr[arr > 7])
Aggregation & Axes: Using .sum() and .mean() with axis=0 (columns) and axis=1 (rows)
Reshaping: Using .reshape() (and the $total elements$ rule)
Broadcasting: How NumPy handles math between different-shaped arrays
Combining Arrays: Using np.vstack() (vertical) and np.hstack() (horizontal)

In [83]:
r=np.arange(12)

In [84]:
print(r.reshape((3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [85]:
num=np.random.rand(2,3)

In [86]:
print(num)

[[0.7653503  0.53129152 0.87013076]
 [0.94823667 0.74832011 0.03943081]]

In [87]:
np.random.randint(100, 200,(5,6))

array([[151, 167, 149, 121, 158, 173],
       [101, 128, 177, 182, 195, 110],
       [129, 183, 161, 135, 197, 186],
       [159, 175, 146, 171, 111, 162],
       [107, 127, 171, 191, 115, 104]])

#simulate rolling a single six-sided die 10 times

In [88]:
np.random.randint(1, 7, 10)

array([1, 1, 5, 1, 3, 1, 1, 4, 3, 5])

In [89]:
np.random.rand(7)

array([0.14593494, 0.17067515, 0.10377293, 0.45770289, 0.43474013,
       0.17623772, 0.77810761])

In [90]:
np.random.rand(3,9)

array([[0.04942758, 0.61499315, 0.59128622, 0.7496011 , 0.94375283,
        0.73472117, 0.37560264, 0.26690701, 0.57153928],
       [0.18583886, 0.37465554, 0.15363516, 0.98484315, 0.54340594,
        0.72271247, 0.06093813, 0.1857539 , 0.95549242],
       [0.87213405, 0.8505221 , 0.24148274, 0.44542734, 0.27906146,
        0.75948702, 0.26837546, 0.1666154 , 0.96238548]])

In [91]:
import numpy as np

scores = np.array([[88, 92],
                   [75, 80],
                   [95, 90]])

In [92]:
np.save("datao.npy",scores)

In [93]:
np.load("datao.npy")

array([[88, 92],
       [75, 80],
       [95, 90]])

In [94]:
np.random.choice(20,7)

array([ 8,  8, 15, 10, 13,  8,  9])

In [95]:
uu=np.random.choice(20,(4,3))

In [96]:
np.save("datammm.npy",uu)

In [97]:
np.load("datammm.npy")

array([[ 7,  1, 11],
       [ 9, 10,  9],
       [ 8,  2,  4],
       [ 4,  5,  3]])

#***PANDAS***

In [98]:
import pandas as pd

In [99]:
bb=[10, 20, 30]

In [100]:
pd.Series(bb)

0    10
1    20
2    30
dtype: int64

In [101]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [102]:
print(s)

a    10
b    20
c    30
dtype: int64

In [103]:
student_data = {
  'Name': ['Alice', 'Bob', 'Charlie'],
  'Score': [85, 92, 78]
}

In [104]:
df = pd.DataFrame(student_data)

In [105]:
print(df)

      Name  Score
0    Alice     85
1      Bob     92
2  Charlie     78

In [106]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [107]:
maths = [22,33,44]
df['math'] = maths
df

      Name  Score  math
0    Alice     85    22
1      Bob     92    33
2  Charlie     78    44

In [108]:
df

      Name  Score  math
0    Alice     85    22
1      Bob     92    33
2  Charlie     78    44

In [109]:
df.loc[1]

Name     Bob
Score     92
math      33
Name: 1, dtype: object

In [110]:
df.loc[1]["Score"]

np.int64(92)

In [111]:
n=df["Score"]>90

In [112]:
print(n)

0    False
1     True
2    False
Name: Score, dtype: bool

In [113]:
df[df["math"] > 30]## give rows

      Name  Score  math
1      Bob     92    33
2  Charlie     78    44

In [114]:
df["Score"] > 80

0     True
1     True
2    False
Name: Score, dtype: bool

In [115]:
df["math"] > 30

0    False
1     True
2     True
Name: math, dtype: bool

In [116]:
(df["Score"] > 80) & (df["math"] > 20)

0     True
1     True
2    False
dtype: bool

In [117]:
df[(df["Score"] > 80) & (df["math"] > 20)]

    Name  Score  math
0  Alice     85    22
1    Bob     92    33

In [118]:
df

      Name  Score  math
0    Alice     85    22
1      Bob     92    33
2  Charlie     78    44

In [119]:
df.loc[2]["math"]

np.int64(44)

In [120]:
df.loc[1]

Name     Bob
Score     92
math      33
Name: 1, dtype: object

In [121]:
df=pd.read_excel("/content/googleplaystore.csv.xlsx")

In [122]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [123]:
df.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [125]:
df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [126]:
df.isnull().sum()

App                  1
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [127]:
df["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [128]:
df["Rating"].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838     True
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [129]:
df["Rating"].isnull().sum()

np.int64(1474)

In [130]:
mean_rating=df["Rating"].mean()

In [131]:
print(mean_rating)

4.193338315362443

In [132]:
df["Rating"]=df['Rating'].fillna(mean_rating)

In [133]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.193338,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [135]:
df=df.dropna(subset=['App'])

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          10840 non-null  float64
 3   Reviews         10840 non-null  object
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10839 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10837 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.2+ MB

In [137]:
df.groupby('Genres').count()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Last Updated,Current Ver,Android Ver
Genres,,,,,,,,,,,,
Action,365,365,365,365,365,365,365,365,365,365,365,365
Action;Action & Adventure,17,17,17,17,17,17,17,17,17,17,17,17
Adventure,75,75,75,75,75,75,75,75,75,75,75,75
Adventure;Action & Adventure,13,13,13,13,13,13,13,13,13,13,13,13
Adventure;Brain Games,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
Video Players & Editors,173,173,173,173,173,173,173,173,173,173,173,173
Video Players & Editors;Creativity,2,2,2,2,2,2,2,2,2,2,2,2
Video Players & Editors;Music & Video,3,3,3,3,3,3,3,3,3,3,3,3
Weather,82,82,82,82,82,82,82,82,82,82,82,82
Word,29,29,29,29,29,29,29,29,29,29,29,29

In [138]:
df.groupby('Genres').size()

Genres
Action                                   365
Action;Action & Adventure                 17
Adventure                                 75
Adventure;Action & Adventure              13
Adventure;Brain Games                      1
                                        ...
Video Players & Editors                  173
Video Players & Editors;Creativity         2
Video Players & Editors;Music & Video      3
Weather                                   82
Word                                      29
Length: 120, dtype: int64

In [139]:
df.groupby('Genres')['Rating'].mean()

Genres
Action                                   4.283708
Action;Action & Adventure                4.311765
Adventure                                4.181156
Adventure;Action & Adventure             4.423077
Adventure;Brain Games                    4.600000
                                           ...
Video Players & Editors                  4.075145
Video Players & Editors;Creativity       4.100000
Video Players & Editors;Music & Video    4.000000
Weather                                  4.239675
Word                                     4.403219
Name: Rating, Length: 120, dtype: float64

In [140]:
df.groupby('Genres')['Rating'].sum()

Genres
Action                                   1563.553368
Action;Action & Adventure                  73.300000
Adventure                                 313.586677
Adventure;Action & Adventure               57.500000
Adventure;Brain Games                       4.600000
                                            ...
Video Players & Editors                   705.000075
Video Players & Editors;Creativity          8.200000
Video Players & Editors;Music & Video      12.000000
Weather                                   347.653368
Word                                      127.693338
Name: Rating, Length: 120, dtype: float64

In [141]:
df['Genres'].nunique()

120